// Platform win ratio stats - QUALIFIED PICKS ONLY (confidence >= 75).
// Keep these values aligned with the historical_bets rebalance migration.
export const platformStats = {
  totalQualified: 3713,
  correctQualified: 3092,
  qualifiedWinRate: 83.3,
  qualifiedWinRateLabel: "83.3%",
  averageConfidence: 82.5,
  streakCurrent: 8,
  streakBest: 18,
  sportBreakdown: [
    { sport: 'NBA', qualified: 1002, wins: 843, winRate: 84.1 },
    { sport: 'Soccer', qualified: 871, wins: 717, winRate: 82.3 },
    { sport: 'NHL', qualified: 835, wins: 685, winRate: 82.0 },
    { sport: 'MLB', qualified: 605, wins: 509, winRate: 84.1 },
    { sport: 'College Baseball', qualified: 132, wins: 112, winRate: 84.8 },
    { sport: 'Table Tennis', qualified: 57, wins: 45, winRate: 78.9 },
    { sport: 'NFL', qualified: 41, wins: 36, winRate: 87.8 },
    { sport: 'UFC', qualified: 38, wins: 31, winRate: 81.6 },
    { sport: 'NCAAB', qualified: 28, wins: 24, winRate: 85.7 },
    { sport: 'CFB', qualified: 17, wins: 14, winRate: 82.4 },
    { sport: 'Tennis', qualified: 15, wins: 13, winRate: 86.7 },
    { sport: 'Golf', qualified: 10, wins: 10, winRate: 100.0 },
    { sport: 'Esports', qualified: 10, wins: 8, winRate: 80.0 },
    { sport: 'Cricket', qualified: 10, wins: 9, winRate: 90.0 },
    { sport: 'Boxing', qualified: 8, wins: 7, winRate: 87.5 },
    { sport: 'Rugby', qualified: 7, wins: 6, winRate: 85.7 },
    { sport: 'Snooker', qualified: 5, wins: 4, winRate: 80.0 },
    { sport: 'Badminton', qualified: 5, wins: 5, winRate: 100.0 },
    { sport: 'Darts', qualified: 5, wins: 4, winRate: 80.0 },
    { sport: 'F1', qualified: 5, wins: 4, winRate: 80.0 },
    { sport: 'NASCAR', qualified: 4, wins: 3, winRate: 75.0 },
    { sport: 'MMA', qualified: 3, wins: 3, winRate: 100.0 },
  ],
};

export const liveUserStats = {
  min: 850,
  max: 1000,
  stepMin: 2,
  stepMax: 7,
  intervalMs: 4500,
  label: "Estimated active bettors live",
  rangeLabel: "850-1,000",
};
