project_id = "fmrcmbdgmhoylmxbapdr"

[functions.betting-chat]
verify_jwt = false

[functions.get-odds]
verify_jwt = false

[functions.get-events]
verify_jwt = false

[functions.get-game-odds]
verify_jwt = false

[functions.scrape-game-data]
verify_jwt = false

[functions.scrape-live-games]
verify_jwt = false

[functions.scrape-picks]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.signup-with-promo]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-ufc-events]
verify_jwt = false
