import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Link } from "react-router-dom";
import { BarChart3, Shield, Target, TrendingUp, Brain, CheckCircle, ArrowRight, Layers, MessageSquare } from "lucide-react";

const faqItems = [
  { q: "What is an AI bet analyzer?", a: "An AI bet analyzer uses machine learning to evaluate any sports bet by calculating true probabilities, identifying value, and scoring risk — giving you a data-driven edge before you place a wager." },
  { q: "How does AI odds analysis work?", a: "Our AI compares sportsbook odds against its own probability model built from thousands of data points including team form, injuries, weather, and historical matchups to find discrepancies." },
  { q: "Is AI betting analysis more accurate than manual research?", a: "AI can process more variables consistently and reduce some forms of emotional bias, but results depend on data quality, model design and market conditions. It should complement—not replace—independent research." },
  { q: "Can I analyze parlays with the AI bet analyzer?", a: "Absolutely. The analyzer breaks down each leg of your parlay, scores correlation risk, and provides an overall probability assessment." },
  { q: "What sports does the AI bet analyzer cover?", a: "ThinkBetAI covers NFL, NBA, MLB, NHL, UFC, soccer, and tennis — with more sports being added regularly." },
  { q: "Is the AI bet analyzer free?", a: "Basic analysis is available on our free tier. Premium subscribers get unlimited deep analysis with advanced risk scoring and real-time updates." },
  { q: "How quickly does the AI analyze a bet?", a: "Analysis is near-instant. Once you enter a matchup and bet type, the AI returns a full probability breakdown, expected value calculation, and risk score in under two seconds." },
  { q: "What's the difference between the bet analyzer and AI picks?", a: "AI picks are proactive recommendations generated by our models. The bet analyzer is reactive — you bring a specific bet and the AI tells you whether it has value. They complement each other perfectly." },
];

const combinedSchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "FAQPage",
      mainEntity: faqItems.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
    {
      "@type": "SoftwareApplication",
      name: "ThinkBetAI Bet Analyzer",
      applicationCategory: "SportsApplication",
      operatingSystem: "Web",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    },
  ],
};

const AIBetAnalyzer = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SEO
        title="AI Bet Analyzer: Probability, Value & Risk"
        description="Analyze a sports bet with AI-assisted probability estimates, implied-odds comparison and risk context for moneylines, spreads, totals and props."
        keywords="ai bet analyzer, betting analysis ai, ai odds analysis, ai bet analysis, sports betting analyzer, bet probability calculator"
        url="/ai-bet-analyzer"
        structuredData={combinedSchema}
      />

      <Header />

      <main className="container mx-auto px-4 py-12 max-w-5xl">
        {/* Hero */}
        <section className="mb-16">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">AI Bet Analyzer for Probability, Value and Risk</h1>
          <p className="text-lg text-muted-foreground max-w-3xl mb-4">
            The <Link to="/ai-bet-analyzer" className="text-primary hover:underline font-medium">AI bet analyzer</Link> evaluates probability, value, and risk using the same betting-analysis framework available across ThinkBetAI.
          </p>
          <p className="text-muted-foreground leading-relaxed max-w-3xl mb-8">
            Stop guessing whether a bet has value. ThinkBetAI's analyzer takes any wager — moneyline, spread, total, or prop — and runs it through our multi-model AI engine to calculate true win probability, expected value, and a comprehensive risk score. Whether you're evaluating a single straight bet or a complex parlay, the <Link to="/ai-bet-analyzer" className="text-primary hover:underline font-medium">AI odds analysis</Link> gives you the data you need before you risk a dollar.
          </p>
          <div className="flex flex-wrap gap-4">
            <Button size="lg" asChild><Link to="/login">Analyze a Bet Now <ArrowRight className="ml-1 h-4 w-4" /></Link></Button>
            <Button size="lg" variant="outline" asChild><Link to="/ai-sports-betting">Learn About AI Betting</Link></Button>
          </div>
        </section>

        {/* How it works */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">How the AI Bet Analyzer Works</h2>
          <div className="prose prose-lg dark:prose-invert max-w-none space-y-4 mb-8">
            <p className="text-muted-foreground leading-relaxed">
              When you submit a bet for analysis, our AI engine kicks off a multi-step evaluation. First, it ingests real-time data for the matchup — current odds from multiple sportsbooks, team and player statistics, injury reports, weather conditions, and historical performance in similar situations. Next, an ensemble of machine learning models (gradient boosting, neural networks, and logistic regression) independently estimate the true probability of each outcome.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              The system then compares its calculated probability against the sportsbook's implied probability to determine expected value (EV). A positive EV means the bet offers more value than the odds suggest — the holy grail of profitable betting. Finally, a risk assessment layer evaluates variance factors like injury uncertainty, weather volatility, and historical line movement to assign a risk score from Low to High.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              The process returns a structured breakdown of the model estimate, implied probability and risk factors. Treat it as one input in your research rather than a guaranteed outcome.
            </p>
          </div>
        </section>

        {/* Probability breakdown */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Probability Breakdown</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { icon: Target, title: "True Win Probability", desc: "Our model calculates the real chance of each outcome, independent of sportsbook odds." },
              { icon: TrendingUp, title: "Expected Value (EV)", desc: "See whether a bet has positive or negative expected value before you place it." },
              { icon: Brain, title: "Confidence Score", desc: "A 0–100 rating showing how confident the AI is in its probability estimate." },
            ].map((item) => (
              <Card key={item.title} variant="glass">
                <CardContent className="p-6">
                  <item.icon className="h-8 w-8 text-primary mb-3" />
                  <h3 className="font-semibold mb-2">{item.title}</h3>
                  <p className="text-sm text-muted-foreground">{item.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        {/* Risk scoring */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Risk Scoring</h2>
          <p className="text-muted-foreground mb-6">
            Every bet is assigned an <Link to="/ai-bet-analyzer" className="text-primary hover:underline font-medium">AI risk score</Link> based on variance, injury impact, historical volatility, and line movement. The analysis flags bets with hidden risk that the odds alone don&apos;t reveal.
          </p>
          <div className="grid md:grid-cols-2 gap-6">
            {[
              { icon: Shield, label: "Low Risk", desc: "Strong data support, minimal variance. High-confidence plays." },
              { icon: BarChart3, label: "Medium Risk", desc: "Solid edge but moderate uncertainty. Suitable for standard bankroll." },
            ].map((item) => (
              <Card key={item.label}>
                <CardContent className="p-6 flex items-start gap-4">
                  <item.icon className="h-8 w-8 text-primary shrink-0" />
                  <div>
                    <h3 className="font-semibold mb-1">{item.label}</h3>
                    <p className="text-sm text-muted-foreground">{item.desc}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        {/* Who it's for */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Who Is the AI Bet Analyzer For?</h2>
          <div className="prose prose-lg dark:prose-invert max-w-none">
            <p className="text-muted-foreground leading-relaxed">
              The AI bet analyzer serves every type of bettor. <strong>Beginners</strong> use it to learn whether a bet makes mathematical sense before placing their first wager. <strong>Intermediate bettors</strong> rely on it to validate their own research and catch value they might have missed. <strong>Advanced handicappers</strong> integrate it into their workflow as a second opinion — a tireless analytical engine that processes data at a scale no human can match.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-3">
              If you've ever placed a bet on gut feeling and wondered whether the numbers actually supported it, the AI bet analyzer gives you that answer in seconds. Pair it with our <Link to="/chat" className="text-primary hover:underline font-medium">AI betting chat</Link> for conversational research or our <Link to="/ai-parlay-builder" className="text-primary hover:underline font-medium">AI parlay builder</Link> for optimized multi-leg bets.
            </p>
          </div>
        </section>

        {/* Real examples */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Real Analysis Example</h2>
          <Card variant="glass">
            <CardContent className="p-6 space-y-4">
              <h3 className="font-semibold text-lg">NFL — Chiefs vs Bills Spread Analysis</h3>
              <ul className="space-y-2">
                {[
                  "AI True Probability: Chiefs -3.5 → 54.2%",
                  "Sportsbook Implied: 51.2%",
                  "Expected Value: +3.0% edge",
                  "Risk Score: Medium (weather variable)",
                  "Confidence: 78/100",
                ].map((line) => (
                  <li key={line} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <CheckCircle className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                    {line}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </section>

        {/* Internal links */}
        <section className="mb-16">
          <h2 className="text-2xl font-semibold mb-6">Explore More AI Betting Tools</h2>
          <div className="grid sm:grid-cols-3 gap-4">
            <Link to="/ai-parlay-builder" className="p-5 rounded-xl border border-border hover:border-primary/30 transition-colors text-center">
              <Layers className="h-8 w-8 text-primary mx-auto mb-2" />
              <span className="font-semibold block">AI Parlay Builder</span>
              <span className="text-xs text-muted-foreground">Build optimized parlays</span>
            </Link>
            <Link to="/chat" className="p-5 rounded-xl border border-border hover:border-primary/30 transition-colors text-center">
              <MessageSquare className="h-8 w-8 text-primary mx-auto mb-2" />
              <span className="font-semibold block">AI Betting Chat</span>
              <span className="text-xs text-muted-foreground">Ask anything about games</span>
            </Link>
            <Link to="/ai-sports-betting" className="p-5 rounded-xl border border-border hover:border-primary/30 transition-colors text-center">
              <Brain className="h-8 w-8 text-primary mx-auto mb-2" />
              <span className="font-semibold block">AI Sports Betting</span>
              <span className="text-xs text-muted-foreground">Learn how AI betting works</span>
            </Link>
          </div>
        </section>

        {/* FAQs */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">FAQs About AI Bet Analysis</h2>
          <Accordion type="single" collapsible className="w-full">
            {faqItems.map((item, i) => (
              <AccordionItem key={i} value={`faq-${i}`}>
                <AccordionTrigger className="text-left">{item.q}</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">{item.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </section>

        {/* CTA */}
        <section className="text-center py-12 rounded-2xl bg-muted/30 border border-border">
          <h2 className="text-2xl font-bold mb-4">Ready to Analyze Your Next Bet?</h2>
          <p className="text-muted-foreground mb-6">Use the <Link to="/ai-bet-analyzer" className="text-primary hover:underline font-medium">AI bet analyzer</Link> to compare model probability, implied odds and risk factors before a wager.</p>
          <div className="flex flex-wrap justify-center gap-4">
            <Button size="lg" asChild><Link to="/login">Start AI Analysis <ArrowRight className="ml-1 h-4 w-4" /></Link></Button>
            <Button size="lg" variant="outline" asChild><Link to="/pricing">View Plans</Link></Button>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default AIBetAnalyzer;
