import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Link } from "react-router-dom";
import { 
  Brain, 
  TrendingUp, 
  Target, 
  Zap, 
  Shield, 
  BarChart3, 
  CheckCircle2, 
  ArrowRight,
  Clock,
  Trophy,
  Sparkles,
  LineChart,
  Users
} from "lucide-react";

const AISportsPicks = () => {
  const sports = [
    { name: "NFL", icon: "🏈" },
    { name: "NBA", icon: "🏀" },
    { name: "MLB", icon: "⚾" },
    { name: "NHL", icon: "🏒" },
    { name: "UFC/MMA", icon: "🥊" },
    { name: "Soccer", icon: "⚽" },
    { name: "Tennis", icon: "🎾" },
    { name: "Table Tennis", icon: "🏓" },
  ];

  const features = [
    {
      icon: Brain,
      title: "Advanced AI Analysis",
      description: "Our proprietary machine learning models analyze thousands of data points including player stats, team performance, injuries, weather, and historical matchups."
    },
    {
      icon: Target,
      title: "Confidence Thresholds",
      description: "Picks are filtered by model confidence and paired with context so you can assess the risk before acting."
    },
    {
      icon: BarChart3,
      title: "Real-Time Odds Tracking",
      description: "Live odds from multiple sportsbooks, line movement tracking, and value identification to help you find the best betting opportunities."
    },
    {
      icon: Shield,
      title: "Risk Assessment",
      description: "Every pick comes with a detailed risk analysis including variance metrics, historical volatility, and situational factors."
    },
    {
      icon: Zap,
      title: "Instant Notifications",
      description: "Get notified the moment a high-value pick is identified. Never miss an opportunity with real-time alerts."
    },
    {
      icon: LineChart,
      title: "Performance Tracking",
      description: "Transparent tracking of all picks with detailed analytics, win rates by sport, and ROI calculations."
    }
  ];

  const howItWorks = [
    {
      step: "1",
      title: "Data Collection",
      description: "The model combines available stats, injury reports, weather conditions and betting-market information."
    },
    {
      step: "2",
      title: "Pattern Recognition",
      description: "Machine-learning models compare matchup patterns and market prices to estimate possible outcomes."
    },
    {
      step: "3",
      title: "Confidence Scoring",
      description: "Each potential pick receives a probability estimate and confidence label based on the available inputs."
    },
    {
      step: "4",
      title: "Delivery & Explanation",
      description: "You receive the pick with a full AI-generated explanation of the reasoning, key factors, and risk assessment."
    }
  ];

  const decisionChecks = [
    {
      title: "Compare probability with price",
      description: "A prediction is only useful when its estimated probability is compared with the sportsbook's implied probability."
    },
    {
      title: "Review the model context",
      description: "Check injuries, lineup news and matchup factors that can change after a prediction is generated."
    },
    {
      title: "Set a risk limit",
      description: "Treat every pick as uncertain, avoid chasing losses and use a stake size you can afford to lose."
    }
  ];

  // Structured data for SEO
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "ThinkBetAI - AI Sports Picks",
    "applicationCategory": "SportsApplication",
    "description": "AI-powered sports betting picks and predictions. Get high-confidence picks for NFL, NBA, MLB, NHL, UFC, Soccer, Tennis and more with detailed AI analysis.",
    "operatingSystem": "Web",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD",
      "description": "Free trial available"
    },
    "featureList": [
      "AI-powered sports predictions",
      "Real-time odds tracking",
      "Multi-sport coverage",
      "Detailed pick explanations",
      "Performance analytics"
    ]
  };

  const faqStructuredData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What are AI sports picks?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "AI sports picks are betting predictions generated by machine learning algorithms that analyze vast amounts of sports data including player statistics, team performance, injuries, weather conditions, and historical trends to identify high-probability betting opportunities."
        }
      },
      {
        "@type": "Question",
        "name": "How accurate are AI sports betting predictions?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Accuracy varies by sport, market, price and time period. ThinkBetAI publishes its qualification criteria and methodology, but no model can guarantee a future result."
        }
      },
      {
        "@type": "Question",
        "name": "Which sports does ThinkBetAI cover?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "ThinkBetAI provides AI-powered picks for NFL, NBA, MLB, NHL, UFC/MMA, Soccer, Tennis, and Table Tennis. We continuously analyze games across all major sports leagues worldwide."
        }
      },
      {
        "@type": "Question",
        "name": "Is using AI for sports betting legal?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes, using AI tools and analytics for sports betting research is completely legal. AI betting assistants simply help you make more informed decisions - the actual betting remains your choice and must comply with your local gambling laws."
        }
      }
    ]
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <SEO 
        title="Free AI Sports Picks Today"
        description="Review free AI sports picks and probability-based predictions for today's NFL, NBA, MLB, NHL, UFC and soccer matchups, with risk context."
        keywords="AI sports picks, AI sports predictions, AI betting picks, machine learning sports betting, AI NFL picks, AI NBA picks, free sports predictions, AI betting algorithm, sports betting AI, best AI sports picks, AI betting predictions 2026"
        url="/ai-sports-picks"
        canonical="https://thinkbetai.com/ai-sports-picks"
        structuredData={structuredData}
      />
      
      {/* Additional FAQ structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData) }}
      />
      
      <Header />
      
      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative py-16 md:py-24 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-accent/5" />
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-transparent to-transparent" />
          
          <div className="container relative z-10">
            <div className="max-w-4xl mx-auto text-center">
              <Badge variant="outline" className="mb-6 px-4 py-1.5 text-sm border-primary/30 bg-primary/5">
                <Sparkles className="h-3.5 w-3.5 mr-1.5 text-primary" />
                Free Picks with Probability Context
              </Badge>
              
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
                Free AI Sports Picks for{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-accent to-primary">
                  Today's Games
                </span>
              </h1>
              
              <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
                <Link to="/login?tab=signup" className="text-primary hover:underline font-medium">Get AI picks today</Link> — review model probabilities, matchup factors and risk notes for the current slate. No prediction guarantees a result.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
                <Button size="lg" className="text-base px-8" asChild>
                  <Link to="/pricing">
                    Get AI Picks Now
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
                <Button size="lg" variant="outline" className="text-base px-8" asChild>
                  <Link to="/picks">
                    View Today's Picks
                  </Link>
                </Button>
              </div>
              
              {/* Trust indicators */}
              <div className="flex flex-wrap justify-center gap-6 text-sm text-muted-foreground">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4 text-green-500" />
                  <span>No credit card required</span>
                </div>
                <div className="flex items-center gap-2">
                  <Users className="h-4 w-4 text-primary" />
                  <span>Plain-language model explanations</span>
                </div>
                <div className="flex items-center gap-2">
                  <Trophy className="h-4 w-4 text-accent" />
                  <span>Transparent result tracking</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Sports Coverage Section */}
        <section className="py-16 bg-card/30">
          <div className="container">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                AI Picks for Every Major Sport
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Sport-specific models account for the inputs that matter in each league. Review predictions across the sports you follow.
              </p>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
              {sports.map((sport) => (
                <div 
                  key={sport.name}
                  className="flex flex-col items-center p-6 rounded-xl bg-background border border-border/50 hover:border-primary/50 transition-colors"
                >
                  <span className="text-4xl mb-3">{sport.icon}</span>
                  <h3 className="font-semibold mb-1">{sport.name}</h3>
                  <span className="text-sm text-primary font-medium">Model analysis available</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-16 md:py-24">
          <div className="container">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Why Our AI Sports Picks Stand Out
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Built by data scientists and sports analysts, our <Link to="/ai-sports-betting" className="text-primary hover:underline font-medium">AI sports betting platform</Link> combines cutting-edge 
                machine learning with deep sports knowledge. Use our <Link to="/ai-bet-analyzer" className="text-primary hover:underline font-medium">AI bet analyzer</Link> for even deeper analysis.
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {features.map((feature, index) => (
                <div 
                  key={index}
                  className="p-6 rounded-xl bg-card border border-border/50 hover:border-primary/30 transition-all hover:shadow-lg"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 mb-4">
                    <feature.icon className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-muted-foreground text-sm">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section className="py-16 bg-gradient-to-b from-background to-card/50">
          <div className="container">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                How Our AI Generates Sports Picks
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                A transparent look at the technology behind our predictions
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-5xl mx-auto">
              {howItWorks.map((step, index) => (
                <div key={index} className="relative">
                  <div className="text-center">
                    <div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary text-primary-foreground text-xl font-bold mx-auto mb-4">
                      {step.step}
                    </div>
                    <h3 className="font-semibold mb-2">{step.title}</h3>
                    <p className="text-sm text-muted-foreground">{step.description}</p>
                  </div>
                  {index < howItWorks.length - 1 && (
                    <div className="hidden lg:block absolute top-7 left-[60%] w-[80%] h-0.5 bg-gradient-to-r from-primary/50 to-transparent" />
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Stats Section */}
        <section className="py-16">
          <div className="container">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl mx-auto">
              <div className="text-center p-6 rounded-xl bg-card border border-border/50">
                <div className="text-3xl md:text-4xl font-bold text-primary mb-2">Public</div>
                <div className="text-sm text-muted-foreground">Methodology</div>
              </div>
              <div className="text-center p-6 rounded-xl bg-card border border-border/50">
                <div className="text-3xl md:text-4xl font-bold text-primary mb-2">4</div>
                <div className="text-sm text-muted-foreground">Market Types</div>
              </div>
              <div className="text-center p-6 rounded-xl bg-card border border-border/50">
                <div className="text-3xl md:text-4xl font-bold text-primary mb-2">8</div>
                <div className="text-sm text-muted-foreground">Sports Covered</div>
              </div>
              <div className="text-center p-6 rounded-xl bg-card border border-border/50">
                <div className="text-3xl md:text-4xl font-bold text-primary mb-2">Daily</div>
                <div className="text-sm text-muted-foreground">Slate Updates</div>
              </div>
            </div>
          </div>
        </section>

        {/* Decision framework */}
        <section className="py-16 bg-card/30">
          <div className="container">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                How to Review an AI Pick
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Use the model as one input in a disciplined decision process, not as a promise of profit.
              </p>
            </div>
            
            <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
              {decisionChecks.map((check) => (
                <div 
                  key={check.title}
                  className="p-6 rounded-xl bg-background border border-border/50"
                >
                  <h3 className="font-semibold text-lg mb-3">{check.title}</h3>
                  <p className="text-muted-foreground">{check.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="py-16">
          <div className="container">
            <div className="max-w-3xl mx-auto">
              <h2 className="text-3xl md:text-4xl font-bold mb-8 text-center">
                Frequently Asked Questions About AI Sports Picks
              </h2>
              
              <div className="space-y-6">
                <div className="p-6 rounded-xl bg-card border border-border/50">
                  <h3 className="font-semibold mb-2">What are AI sports picks?</h3>
                  <p className="text-muted-foreground text-sm">
                    AI sports picks are betting predictions generated by machine learning algorithms that analyze 
                    vast amounts of sports data including player statistics, team performance, injuries, weather 
                    conditions, and historical trends to identify high-probability betting opportunities.
                  </p>
                </div>
                
                <div className="p-6 rounded-xl bg-card border border-border/50">
                  <h3 className="font-semibold mb-2">How accurate are AI sports betting predictions?</h3>
                  <p className="text-muted-foreground text-sm">
                    Accuracy varies by sport, market, price and time period. ThinkBetAI publishes its
                    qualification criteria and methodology, but no model can guarantee a future result.
                  </p>
                </div>
                
                <div className="p-6 rounded-xl bg-card border border-border/50">
                  <h3 className="font-semibold mb-2">Which sports does ThinkBetAI cover?</h3>
                  <p className="text-muted-foreground text-sm">
                    ThinkBetAI provides AI-powered picks for NFL, NBA, MLB, NHL, UFC/MMA, Soccer, Tennis, 
                    and Table Tennis. We continuously analyze games across all major sports leagues worldwide.
                  </p>
                </div>
                
                <div className="p-6 rounded-xl bg-card border border-border/50">
                  <h3 className="font-semibold mb-2">Is using AI for sports betting legal?</h3>
                  <p className="text-muted-foreground text-sm">
                    Yes, using AI tools and analytics for sports betting research is completely legal. AI 
                    betting assistants simply help you make more informed decisions - the actual betting 
                    remains your choice and must comply with your local gambling laws.
                  </p>
                </div>
                
                <div className="p-6 rounded-xl bg-card border border-border/50">
                  <h3 className="font-semibold mb-2">How do I get started with AI sports picks?</h3>
                  <p className="text-muted-foreground text-sm">
                    Simply create a free account to access our daily AI picks. For full access to all features, 
                    detailed analysis, and real-time notifications, upgrade to a premium subscription.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 bg-gradient-to-r from-primary/10 via-accent/10 to-primary/10">
          <div className="container">
            <div className="max-w-3xl mx-auto text-center">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Start Winning with AI Sports Picks Today
              </h2>
              <p className="text-muted-foreground mb-8">
                Review AI-assisted picks with probability estimates, matchup context and explicit uncertainty.
                No credit card required to start.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button size="lg" className="text-base px-8" asChild>
                  <Link to="/pricing">
                    Get Started Free
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
                <Button size="lg" variant="outline" className="text-base px-8" asChild>
                  <Link to="/faq">
                    Learn More
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default AISportsPicks;
