import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { seoBlueprints } from "../src/seo/blueprints";

const routes = seoBlueprints
  .map((blueprint) => blueprint.canonical)
  .sort((a, b) => a.localeCompare(b));

const file = [
  "// Generated by scripts/generate-seo-route-manifest.ts",
  "// Keep the browser route table lightweight; full blueprint content is lazy-loaded.",
  "export const seoBlueprintRoutes = [",
  ...routes.map((route) => `  ${JSON.stringify(route)},`),
  "] as const;",
  "",
].join("\n");

writeFileSync(resolve("src/seo/blueprintRoutes.generated.ts"), file);
console.log(`✓ blueprintRoutes.generated.ts written (${routes.length} routes)`);
