import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SEO_LANDING_CONFIGS } from "../src/lib/seoLandingConfigs";
import { blogPosts } from "../src/lib/blogData";
import { CORE_SEO_PATHS } from "../src/seoCorePages";
import { SEO_ALIAS_REDIRECTS, isSeoAlias } from "../src/seoAliases";
import { seoBlueprints } from "../src/seo/blueprints";
import { APP_SHELL_REWRITES } from "../src/appShellPages";
import { localizedMoneyPageRedirects } from "../src/localizedSeoPages";

const blueprintPaths = new Set(seoBlueprints.map((blueprint) => blueprint.canonical));

const lines = [
  "# Generated by scripts/generate-redirects.ts",
  "# Retired programmatic pages redirect to indexable public hubs.",
  "/predictions/* /ai-sports-picks 301",
  "/teams/* /ai-sports-picks 301",
  "/matchups/* /ai-sports-picks 301",
  "/players/* /ai-player-props 301",
  "/props/* /ai-player-props 301",
  "",
  "# Consolidated aliases first so they resolve as permanent redirects.",
  ...Object.entries(SEO_ALIAS_REDIRECTS).map(
    ([slug, destination]) => `/${slug} ${destination} 301`,
  ),
  ...localizedMoneyPageRedirects.map(({ source, target }) => `${source} ${target} 301`),
  "",
  "# Serve crawler-readable prerendered HTML while React takes over in-browser.",
  ...CORE_SEO_PATHS.filter((path) => path !== "/" && !blueprintPaths.has(path)).map(
    (path) => `${path} ${path}.html 200`,
  ),
  ...seoBlueprints.map((blueprint) => `${blueprint.canonical} ${blueprint.canonical}.html 200`),
  ...SEO_LANDING_CONFIGS.filter(
    (config) => !isSeoAlias(config.slug) && !blueprintPaths.has(`/${config.slug}`),
  ).map(
    (config) => `/${config.slug} /${config.slug}.html 200`,
  ),
  "/blog /blog.html 200",
  ...blogPosts.map((post) => `/blog/${post.slug} /blog/${post.slug}.html 200`),
  "",
  "# Private app routes get noindex shells instead of the homepage catch-all.",
  ...APP_SHELL_REWRITES.map(({ source, target }) => `${source} ${target} 200`),
  "",
  "# Hard fallback for unknown URLs. Real SPA routes must be listed above.",
  "/* /404.html 404",
  "",
];

writeFileSync(resolve("public/_redirects"), lines.join("\n"));
console.log(`✓ _redirects written (${lines.length} rules/comments)`);
